pybo/views/answer_views.py
from datetime import datetime

from flask import Blueprint, url_for, request
from werkzeug.utils import redirect

from pybo import db

from pybo.models import Question, Answer

from flask import render_template
from ..forms import AnswerForm

from flask import g
from .auth_views import login_required

from flask import flash

bp = Blueprint('answer', __name__, url_prefix='/answer')

@bp.route('/create/<int:question_id>', methods=('POST',))
@login_required
def create(question_id) :
    '''

    question = Question.query.get_or_404(question_id)

    ## request로 question_detail.html의 form 태그에 있는 content를 가져옴
    content = request.form['content']

    ## answer 생성 (models.py 참고)
    answer = Answer(content = content, create_date = datetime.now())

    ## 이 함수가 db.session.add()를 대신함!!
    question.answer_set.append(answer)

    ## db에 commit
    db.session.commit()
    return redirect(url_for('question.detail', question_id = question_id))
    '''
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(content=content, create_date=datetime.now(), user=g.user) 
        question.answer_set.append(answer)
        db.session.commit()

        return redirect(f"{url_for('question.detail', question_id=question_id)}#answer_{answer.id}")
    
    
    return render_template('question/question_detail.html', question=question, form=form)


## 답변 수정 라우팅 함수
@bp.route('/modify/<int:answer_id>', methods=('GET', 'POST'))
@login_required
def modify(answer_id) :
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user :
        flash('본인 답변만 수정할 수 있습니다.')
        return redirect(url_for('question.detail', question_id=answer.question.id))
    
    if request.method == 'POST' :
        form = AnswerForm()
        if form.validate_on_submit() :
            form.populate_obj(answer)
            answer.modify_date = datetime.now() ## 수정 시각 저장
            db.session.commit()

            return redirect(f"{url_for('question.detail', question_id=answer.question.id)}#answer_{answer.id}")
    
    else : ## 수정 버튼을 누르는 경우!!!!!!!
        form = AnswerForm(obj=answer)
    
    return render_template('answer/answer_form.html', form=form)

## 삭제를 위한 라우팅 함수
@bp.route('/delete/<int:answer_id>')
@login_required
def delete(answer_id) :
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user :
        flash('타인의 답변은 삭제할 수 없습니다.')
    
    else :
        db.session.delete(answer)
        db.session.commit()
    
    return redirect(url_for('question.detail', question_id=question_id))

## 추천를 위한 라우팅 함수
@bp.route('/vote/<int:answer_id>/')
@login_required
def vote(answer_id) :
    _answer = Answer.query.get_or_404(answer_id)
    if g.user == _answer.user :
        flash('본인 답변엔 추천할 수 없습니다.')
    
    else :
        _answer.voter.append(g.user)
        db.session.commit()
    
    return redirect(f"{url_for('question.detail', question_id=_answer.question.id)}#answer_{_answer.id}")

pybo/views/question_views.py
from flask import Blueprint, render_template

from pybo.models import Question

from pybo.forms import QuestionForm, AnswerForm

from datetime import datetime
from flask import request, url_for
from werkzeug.utils import redirect
from .. import db

from flask import g
from pybo.views.auth_views import login_required

from flask import flash

from ..models import Question, Answer, User

bp = Blueprint('question', __name__, url_prefix='/question')


'''
main_views.py와 똑같아 보이지만 prefix 다르게 했고, 
route도 좀 더 상세하게 바꿈 !!

=> __init__ 도 수정해야됨
'''

@bp.route('/list/')
def _list() :
    page = request.args.get('page', type=int, default=1)  # 페이지
    
    kw = request.args.get('kw', type=str, default='')


    question_list = Question.query.order_by(Question.create_date.desc())

    if kw :
        search = f'%%{kw}%%'
        sub_query = db.session.query(Answer.question_id, Answer.content, User.username)\
            .join(User, Answer.user_id == User.id).subquery()
        question_list = question_list\
            .join(User)\
            .outerjoin(sub_query, sub_query.c.question_id == Question.id)\
            .filter(Question.subject.ilike(search) | ## 질문제목
                    Question.content.ilike(search) | ## 질문내용
                    User.username.ilike(search) |   ## 질문작성자
                    sub_query.c.content.ilike(search) | ## 답변내용
                    sub_query.c.username.ilike(search) ## 답변작성자
            )\
            .distinct() ## 중복제거
    question_list = question_list.paginate(page, per_page=10)
    return render_template('question/question_list.html', question_list = question_list, page=page, kw=kw)

@bp.route('/detail/<int:question_id>/')
def detail(question_id) :
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question, form=form)

@bp.route('/create/', methods = ('GET', 'POST')) ## 질문 작성을 들어갈 때
@login_required ## 로그인이 필요한 서비스라는 제약을 걸어줌
def create() :
    form = QuestionForm()

    ## 여기부터 데이터를 db에 저장하는 코드
    ## POST로 지정했기 때문에 이제 POST인 경우[저장하기]엔 아래의 코드를 실행해서 return 하고
    if request.method == 'POST' and form.validate_on_submit() : ##validate_on_submit()은 전송된 폼 데이터의 정합성 점검
        question = Question(subject = form.subject.data, content = form.content.data, create_date = datetime.now(), user=g.user)
        db.session.add(question)
        db.session.commit()
        
        return redirect(url_for('main.index'))

    ## Post가 아닌 get인 경우[질문 등록하기]에는 아래를 return 함
    return render_template('question/question_form.html', form=form)

## 질문 수정을 위한 라우팅 함수
@bp.route('/modify/<int:question_id>', methods=('GET','POST'))
@login_required
def modify(question_id) :
    question = Question.query.get_or_404(question_id)
    if g.user != question.user :
        flash('너가 쓴 글 아니잖아여!!!!')
        return redirect(url_for('question.detail', question_id=question_id))
    
    if request.method == 'POST' : ## 수정하고 저장하기 버튼을 눌렀을 경우임!
        form = QuestionForm() 
        if form.validate_on_submit() :
            form.populate_obj(question)
            question.modify_date = datetime.now() ## 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id = question_id))

    else : ## get 요청인 경우 = 질문 수정 버튼을 눌렀을 경우
        form = QuestionForm(obj=question) ## question의 내용이 담겨져서 나옴!!
    return render_template('question/question_form.html', form=form)


## 질문 삭제를 위한 라우팅 함수
@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id) :
    question = Question.query.get_or_404(question_id)
    if g.user != question.user :
        flash('다른 사람 글은 삭제 못해용~')
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(question) ## db에서 question에 해당되는 내용 삭제
    db.session.commit()
    return redirect(url_for('question._list'))


## 질문 추천을 위한 라우팅 함수
@bp.route('/vote/<int:question_id>/')
@login_required
def vote(question_id) :
    _question = Question.query.get_or_404(question_id)
    if g.user == _question.user :
        flash('본인 질문엔 추천할 수 없습니다.')
    
    else :
        _question.voter.append(g.user)
        db.session.commit()
    
    return redirect(url_for('question.detail', question_id = question_id))

pybo/templates/question/question_detail.html
<!--
<! 이건 css 적용>
<link rel = "stylesheet" href="{{ url_for('static', filename='style.css')}}">

<!질문 제목과 내용을 표시해줌!!  >
<h1>{{ question.subject }}</h1>
<div>
    {{ question.content }}
</div>

<! 답변은 질문 밑에 표시돼야 하므로 여기에다가 표시 >
<h5>{{ question.answer_set|length}}개의 답변이 있습니다.</h5>
<div>
    <ul>
    {% for answer in question.answer_set %}
        <li>{{ answer.content }}</li>
    {% endfor %}
    </ul>
</div>


<! 답변 저장을 위한 엘리먼트>
<form action = "{{ url_for('answer.create', question_id = question.id) }}" method = "post">
    <textarea name="'content" id ='content', rows="'15"></textarea>
    <input type = "submit" value="답변등록">
    <! 답변등록 버튼을 우르면 URL이 호출됨 >
</form>

-->


<!-- 부트스트랩 적용 후 -->

<!-- 표준 템플릿을 상속 받으므로 아래의 코드는 필요 없어짐 -->
<!-- <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}"> -->

{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- flash 에러 표시 -->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}

    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ question.content|markdown }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modiry_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date|datetime }}</div>
                </div>
                {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.user.username }}</div>
                    <div>{{ question.create_date|datetime }}</div>
                </div>
            </div>
            <div class="my-3">
                <!-- 추천 버튼 -->
                <a href="javascript:void(0)" data-uri="{{ url_for('question.vote', question_id=question.id) }}"
                class="recommend btn btn-sm btn-outline-secondary">추천
                <span class="badge rounded-pill bg-success">{{ question.voter|length }}</span>
            </a>

                {% if g.user == question.user %}
                <a href="{{ url_for('question.modify', question_id=question.id) }}" 
                class="btn btn-sm btn-outline-secondary">수정</a>
                
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                data-uri="{{ url_for('question.delete', question_id = question.id) }}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>


    <!-- 답변 목록 -->
    <h5 class="border-bottom my-3 py-2">{{ question.answer_set|length }}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set %}
    <a id="answer_{{ answer.id }}"></a> <!-- Anchor Element!! -->
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ answer.content|markdown }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
                <div class="badge bg-light text-dark p-2 text-start mx-3">
                    <div class="mb-2">midified at</div>
                </div>
                {% endif %}
                
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.user.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                <!-- 추천 버튼 -->
                <a href="javascript:void(0)" data-uri="{{ url_for('answer.vote', answer_id=answer.id) }}"
                class="recommend btn btn-sm btn-outline-secondary">추천
                <span class="badge rounded-pill bg-success">{{ answer.voter|length }}</span>
                </a>
                {% if g.user == answer.user %}
                <a href="{{ url_for('answer.modify', answer_id=answer.id) }}"
                class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}


    <!-- 답변 등록 -->
    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        
        <div class="mb-3">
            <textarea {% if not g.user %}disabled{% endif %}
            name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
<!-- JS 확인창 for 삭제-->
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("진짜 삭제 할시롱?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements= document.getElementsByClassName('recommend');
Array.from(recommend_elements).forEach(function(element){
    element.addEventListener('click', function(){
        if(confirm('정말로 추천하시겠습니까?')){
            location.href= this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 질문 등록 -->
<div class = "container">
    <h5 class = "my-3 border-bottoom pb-2">질문등록</h5>
    <form method = 'post' class ='my-3'>
        <!-- For CSRF 토큰 -->
        {{ form.csrf_token }}

        <!-- 오류 표시 -->
        {% if form.errors %}
        <div class= "alert alert-danger" role = "alert">
            {% for field, errors in form.errors.items() %}
            <strong>{{ form[field].label }}</strong>
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endfor %}
        </div>
        {% endif %}
        
        
        <!-- 이건 폼 자동 생성 ver (이걸 쓰긴 할듯..) 
        {{ form.subject.label }} < 라벨 표시 >
        {{ form.subject(class = "form-control") }}     < 입력폼 표시 >

        {{ form.content.label }}
        {{ form.content(class = "form-control") }}

        <button type = 'submit' class = 'btn btn-primary'>저장하기</button> -->
    
    
        <!-- HTML 코드로 똑같은 화면 만들기 -->
        <div class="mb-3">
            <label for="subject">제목</label>
            <!-- value = "~~~" : 이미 전송한 데이터가 다시 설정
            or '' : 기존 값이 없으면 ''로 처리-->
            <input type="text" class="form-control" name="subject" id="subject"
            value = "{{ form.subject.date or '' }}"> 
        </div>
        <div class="mb-3">

            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10"></textarea>
        
        </div>

        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

<!-- 
form 태그의 method가 post 이기 때문에 입력 데이터는 post로 전송됨
그러나   question_view.py의 create 라우팅 함수는 method를 지정 안 했기 때문에
가장 기본 방식인 get 만 처리 가능 
=> post도 처리 가능하게 create 라우팅 함수를 처리해야함

-->

pybo/templates/question/question_list.html
<!--여기부터는 Bootstrap 적용 후 --> 

<!-- 이제 표준 템플릿을 상속 받으므로 이렇게 넣어줄 필요가 없음-->
<!--<link rel = 'stylesheet' href="{{url_for('static', filename='bootstrap.min.css') }}">-->

{% extends 'base.html' %}
{% block content %}
<div class = "container my-3"> <!-- 부트스트랩 제공 클래스 -->
    <!-- 검색 기능!! -->
    <div class="row my-30">
        <div class="col-6">
            <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw or '' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div> 
    <table class="table">   <!-- 부트스트랩 제공 클래스 -->
        <thead>
        <tr class="table-dark"> <!-- 부트스트랩 제공 클래스 -->
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>

        <tbody>
        {% if question_list %}
        {% for question in question_list.items %}
        <tr class="text-center">
            <td>{{ question_list.total - ((question_list.page-1) * question_list.per_page) - loop.index0 }}</td>
            <td class="text-start">
                <a href = "{{ url_for('question.detail', question_id=question.id)}}">{{ question.subject }}</a>
                {% if question.answer_set|length > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set|length }}</span>
                {% endif %}
    
            </td>
            <td>{{ question.user.username }}</td> <!-- 글쓴이 추가 !!-->
            <td>{{ question.create_date|datetime }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan = "3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>

    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_prev %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.prev_num }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        <!-- 페이지번호 -->
        {% for page_num in question_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != question_list.page %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="disabled">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_num }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <!--질문 등록 버튼-->
</div>
<!-- page와 kw를 GET 방식으로 하기 위한 form -->
<form id="searchForm" method="get" action="{{ url_for('question._list') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
// page-link가 class이름인 걸 누르면 searchForm을 요청함
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
// 검색버튼 클릭 시 kw SeachForm 요청
const btn_search = document.getElementById('btn_search');
btn_search.addEventListener('click', function(){
    document.getElementById('kw').value = document.getElementById('search_kw').value; 
    document.getElementById('page').value = 1;// 검색 버튼 클릭 시 1페이지부터 조회
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}